"""
country.py

Fundamental definition for Country metadata.
Contains information about a country that does not frequently change,
and that groups do not have different opinions about.
Furthermore, contains the base data on which other information can be attached.

name: The name of the country in English.
alpha2: The two-letter country code.
    Also referred to as ISO2 or CCA2
alpha3: The three-letter country code.
    Also referred to as ISO3 or CCA3
numeric: The numeric country code.
    Also referred to as UNSDM49 or CCN3
apolitical_name: The name of the country in English, without any political connotations.
"""
from dataclasses import dataclass


@dataclass
class Country:
    name: str
    alpha2: str
    alpha3: str
    numeric: int
    apolitical_name: str


countries = [
    Country(
        name='Afghanistan',
        alpha2='AF',
        alpha3='AFG',
        numeric=4,
        apolitical_name='Afghanistan',
    ),
    Country(
        name='Åland Islands',
        alpha2='AX',
        alpha3='ALA',
        numeric=248,
        apolitical_name='Åland Islands',
    ),
    Country(
        name='Albania',
        alpha2='AL',
        alpha3='ALB',
        numeric=8,
        apolitical_name='Albania',
    ),
    Country(
        name='Algeria',
        alpha2='DZ',
        alpha3='DZA', numeric=12,
        apolitical_name='Algeria',
    ),
    Country(
        name='American Samoa',
        alpha2='AS',
        alpha3='ASM',
        numeric=16,
        apolitical_name='American Samoa',
    ),
    Country(
        name='Andorra',
        alpha2='AD',
        alpha3='AND',
        numeric=20,
        apolitical_name='Andorra',
    ),
    Country(
        name='Angola',
        alpha2='AO',
        alpha3='AGO',
        numeric=24,
        apolitical_name='Angola',
    ),
    Country(
        name='Anguilla',
        alpha2='AI',
        alpha3='AIA',
        numeric=660,
        apolitical_name='Anguilla',
    ),
    Country(
        name='Antarctica',
        alpha2='AQ',
        alpha3='ATA',
        numeric=10,
        apolitical_name='Antarctica',
    ),
    Country(
        name='Antigua and Barbuda',
        alpha2='AG',
        alpha3='ATG',
        numeric=28,
        apolitical_name='Antigua and Barbuda',
    ),
    Country(
        name='Argentina',
        alpha2='AR',
        alpha3='ARG',
        numeric=32,
        apolitical_name='Argentina',
    ),
    Country(
        name='Armenia',
        alpha2='AM',
        alpha3='ARM',
        numeric=51,
        apolitical_name='Armenia',
    ),
    Country(
        name='Aruba',
        alpha2='AW',
        alpha3='ABW',
        numeric=533,
        apolitical_name='Aruba',
    ),
    Country(
        name='Australia',
        alpha2='AU',
        alpha3='AUS',
        numeric=36,
        apolitical_name='Australia',
    ),
    Country(
        name='Austria',
        alpha2='AT',
        alpha3='AUT',
        numeric=40,
        apolitical_name='Austria',
    ),
    Country(
        name='Azerbaijan',
        alpha2='AZ',
        alpha3='AZE',
        numeric=31,
        apolitical_name='Azerbaijan',
    ),
    Country(
        name='Bahamas',
        alpha2='BS',
        alpha3='BHS',
        numeric=44,
        apolitical_name='Bahamas',
    ),
    Country(
        name='Bahrain',
        alpha2='BH',
        alpha3='BHR',
        numeric=48,
        apolitical_name='Bahrain',
    ),
    Country(
        name='Bangladesh',
        alpha2='BD',
        alpha3='BGD',
        numeric=50,
        apolitical_name='Bangladesh',
    ),
    Country(
        name='Barbados',
        alpha2='BB',
        alpha3='BRB',
        numeric=52,
        apolitical_name='Barbados',
    ),
    Country(
        name='Belarus',
        alpha2='BY',
        alpha3='BLR',
        numeric=112,
        apolitical_name='Belarus',
    ),
    Country(
        name='Belgium',
        alpha2='BE',
        alpha3='BEL',
        numeric=56,
        apolitical_name='Belgium',
    ),
    Country(
        name='Belize',
        alpha2='BZ',
        alpha3='BLZ',
        numeric=84,
        apolitical_name='Belize',
    ),
    Country(
        name='Benin',
        alpha2='BJ',
        alpha3='BEN',
        numeric=204,
        apolitical_name='Benin',
    ),
    Country(
        name='Bermuda',
        alpha2='BM',
        alpha3='BMU',
        numeric=60,
        apolitical_name='Bermuda',
    ),
    Country(
        name='Bhutan',
        alpha2='BT',
        alpha3='BTN',
        numeric=64,
        apolitical_name='Bhutan',
    ),
    Country(
        name='Bolivia, Plurinational State of',
        alpha2='BO',
        alpha3='BOL',
        numeric=68,
        apolitical_name='Bolivia, Plurinational State of',
    ),
    Country(
        name='Bonaire, Sint Eustatius and Saba',
        alpha2='BQ',
        alpha3='BES',
        numeric=535,
        apolitical_name='Bonaire, Sint Eustatius and Saba',
    ),
    Country(
        name='Bosnia and Herzegovina',
        alpha2='BA',
        alpha3='BIH',
        numeric=70,
        apolitical_name='Bosnia and Herzegovina',
    ),
    Country(
        name='Botswana',
        alpha2='BW',
        alpha3='BWA',
        numeric=72,
        apolitical_name='Botswana',
    ),
    Country(
        name='Bouvet Island',
        alpha2='BV',
        alpha3='BVT',
        numeric=74,
        apolitical_name='Bouvet Island',
    ),
    Country(
        name='Brazil',
        alpha2='BR',
        alpha3='BRA',
        numeric=76,
        apolitical_name='Brazil',
    ),
    Country(
        name='British Indian Ocean Territory',
        alpha2='IO',
        alpha3='IOT',
        numeric=86,
        apolitical_name='British Indian Ocean Territory',
    ),
    Country(
        name='Brunei Darussalam',
        alpha2='BN',
        alpha3='BRN',
        numeric=96,
        apolitical_name='Brunei Darussalam',
    ),
    Country(
        name='Bulgaria',
        alpha2='BG',
        alpha3='BGR',
        numeric=100,
        apolitical_name='Bulgaria',
    ),
    Country(
        name='Burkina Faso',
        alpha2='BF',
        alpha3='BFA',
        numeric=854,
        apolitical_name='Burkina Faso',
    ),
    Country(
        name='Burundi',
        alpha2='BI',
        alpha3='BDI',
        numeric=108,
        apolitical_name='Burundi',
    ),
    Country(
        name='Cambodia',
        alpha2='KH',
        alpha3='KHM',
        numeric=116,
        apolitical_name='Cambodia',
    ),
    Country(
        name='Cameroon',
        alpha2='CM',
        alpha3='CMR',
        numeric=120,
        apolitical_name='Cameroon',
    ),
    Country(
        name='Canada',
        alpha2='CA',
        alpha3='CAN',
        numeric=124,
        apolitical_name='Canada',
    ),
    Country(
        name='Cabo Verde',
        alpha2='CV',
        alpha3='CPV',
        numeric=132,
        apolitical_name='Cabo Verde',
    ),
    Country(
        name='Cayman Islands',
        alpha2='KY',
        alpha3='CYM',
        numeric=136,
        apolitical_name='Cayman Islands',
    ),
    Country(
        name='Central African Republic',
        alpha2='CF',
        alpha3='CAF',
        numeric=140,
        apolitical_name='Central African Republic',
    ),
    Country(
        name='Chad',
        alpha2='TD',
        alpha3='TCD',
        numeric=148,
        apolitical_name='Chad',
    ),
    Country(
        name='Chile',
        alpha2='CL',
        alpha3='CHL',
        numeric=152,
        apolitical_name='Chile',
    ),
    Country(
        name='China',
        alpha2='CN',
        alpha3='CHN',
        numeric=156,
        apolitical_name='China',
    ),
    Country(
        name='Christmas Island',
        alpha2='CX',
        alpha3='CXR',
        numeric=162,
        apolitical_name='Christmas Island',
    ),
    Country(
        name='Cocos (Keeling) Islands',
        alpha2='CC',
        alpha3='CCK',
        numeric=166,
        apolitical_name='Cocos (Keeling) Islands',
    ),
    Country(
        name='Colombia',
        alpha2='CO',
        alpha3='COL',
        numeric=170,
        apolitical_name='Colombia',
    ),
    Country(
        name='Comoros',
        alpha2='KM',
        alpha3='COM',
        numeric=174,
        apolitical_name='Comoros',
    ),
    Country(
        name='Congo',
        alpha2='CG',
        alpha3='COG',
        numeric=178,
        apolitical_name='Congo',
    ),
    Country(
        name='Congo, Democratic Republic of the',
        alpha2='CD',
        alpha3='COD',
        numeric=180,
        apolitical_name='Congo, Democratic Republic of the',
    ),
    Country(
        name='Cook Islands',
        alpha2='CK',
        alpha3='COK',
        numeric=184,
        apolitical_name='Cook Islands',
    ),
    Country(
        name='Costa Rica',
        alpha2='CR',
        alpha3='CRI',
        numeric=188,
        apolitical_name='Costa Rica',
    ),
    Country(
        name="Côte d'Ivoire",
        alpha2='CI',
        alpha3='CIV',
        numeric=384,
        apolitical_name="Côte d'Ivoire",
    ),
    Country(
        name='Croatia',
        alpha2='HR',
        alpha3='HRV',
        numeric=191,
        apolitical_name='Croatia',
    ),
    Country(
        name='Cuba',
        alpha2='CU',
        alpha3='CUB',
        numeric=192,
        apolitical_name='Cuba',
    ),
    Country(
        name='Curaçao',
        alpha2='CW',
        alpha3='CUW',
        numeric=531,
        apolitical_name='Curaçao',
    ),
    Country(
        name='Cyprus',
        alpha2='CY',
        alpha3='CYP',
        numeric=196,
        apolitical_name='Cyprus',
    ),
    Country(
        name='Czechia',
        alpha2='CZ',
        alpha3='CZE',
        numeric=203,
        apolitical_name='Czechia',
    ),
    Country(
        name='Denmark',
        alpha2='DK',
        alpha3='DNK',
        numeric=208,
        apolitical_name='Denmark',
    ),
    Country(
        name='Djibouti',
        alpha2='DJ',
        alpha3='DJI',
        numeric=262,
        apolitical_name='Djibouti',
    ),
    Country(
        name='Dominica',
        alpha2='DM',
        alpha3='DMA',
        numeric=212,
        apolitical_name='Dominica',
    ),
    Country(
        name='Dominican Republic',
        alpha2='DO',
        alpha3='DOM',
        numeric=214,
        apolitical_name='Dominican Republic',
    ),
    Country(
        name='Ecuador',
        alpha2='EC',
        alpha3='ECU',
        numeric=218,
        apolitical_name='Ecuador',
    ),
    Country(
        name='Egypt',
        alpha2='EG',
        alpha3='EGY',
        numeric=818,
        apolitical_name='Egypt',
    ),
    Country(
        name='El Salvador',
        alpha2='SV',
        alpha3='SLV',
        numeric=222,
        apolitical_name='El Salvador',
    ),
    Country(
        name='Equatorial Guinea',
        alpha2='GQ',
        alpha3='GNQ',
        numeric=226,
        apolitical_name='Equatorial Guinea',
    ),
    Country(
        name='Eritrea',
        alpha2='ER',
        alpha3='ERI',
        numeric=232,
        apolitical_name='Eritrea',
    ),
    Country(
        name='Estonia',
        alpha2='EE',
        alpha3='EST',
        numeric=233,
        apolitical_name='Estonia',
    ),
    Country(
        name='Ethiopia',
        alpha2='ET',
        alpha3='ETH',
        numeric=231,
        apolitical_name='Ethiopia',
    ),
    Country(
        name='Falkland Islands (Malvinas)',
        alpha2='FK',
        alpha3='FLK',
        numeric=238,
        apolitical_name='Falkland Islands (Malvinas)',
    ),
    Country(
        name='Faroe Islands',
        alpha2='FO',
        alpha3='FRO',
        numeric=234,
        apolitical_name='Faroe Islands',
    ),
    Country(
        name='Fiji',
        alpha2='FJ',
        alpha3='FJI',
        numeric=242,
        apolitical_name='Fiji',
    ),
    Country(
        name='Finland',
        alpha2='FI',
        alpha3='FIN',
        numeric=246,
        apolitical_name='Finland',
    ),
    Country(
        name='France',
        alpha2='FR',
        alpha3='FRA',
        numeric=250,
        apolitical_name='France',
    ),
    Country(
        name='French Guiana',
        alpha2='GF',
        alpha3='GUF',
        numeric=254,
        apolitical_name='French Guiana',
    ),
    Country(
        name='French Polynesia',
        alpha2='PF',
        alpha3='PYF',
        numeric=258,
        apolitical_name='French Polynesia',
    ),
    Country(
        name='French Southern Territories',
        alpha2='TF',
        alpha3='ATF',
        numeric=260,
        apolitical_name='French Southern Territories',
    ),
    Country(
        name='Gabon',
        alpha2='GA',
        alpha3='GAB',
        numeric=266,
        apolitical_name='Gabon',
    ),
    Country(
        name='Gambia',
        alpha2='GM',
        alpha3='GMB',
        numeric=270,
        apolitical_name='Gambia',
    ),
    Country(
        name='Georgia',
        alpha2='GE',
        alpha3='GEO',
        numeric=268,
        apolitical_name='Georgia',
    ),
    Country(
        name='Germany',
        alpha2='DE',
        alpha3='DEU',
        numeric=276,
        apolitical_name='Germany',
    ),
    Country(
        name='Ghana',
        alpha2='GH',
        alpha3='GHA',
        numeric=288,
        apolitical_name='Ghana',
    ),
    Country(
        name='Gibraltar',
        alpha2='GI',
        alpha3='GIB',
        numeric=292,
        apolitical_name='Gibraltar',
    ),
    Country(
        name='Greece',
        alpha2='GR',
        alpha3='GRC',
        numeric=300,
        apolitical_name='Greece',
    ),
    Country(
        name='Greenland',
        alpha2='GL',
        alpha3='GRL',
        numeric=304,
        apolitical_name='Greenland',
    ),
    Country(
        name='Grenada',
        alpha2='GD',
        alpha3='GRD',
        numeric=308,
        apolitical_name='Grenada',
    ),
    Country(
        name='Guadeloupe',
        alpha2='GP',
        alpha3='GLP',
        numeric=312,
        apolitical_name='Guadeloupe',
    ),
    Country(
        name='Guam',
        alpha2='GU',
        alpha3='GUM',
        numeric=316,
        apolitical_name='Guam',
    ),
    Country(
        name='Guatemala',
        alpha2='GT',
        alpha3='GTM',
        numeric=320,
        apolitical_name='Guatemala',
    ),
    Country(
        name='Guernsey',
        alpha2='GG',
        alpha3='GGY',
        numeric=831,
        apolitical_name='Guernsey',
    ),
    Country(
        name='Guinea',
        alpha2='GN',
        alpha3='GIN',
        numeric=324,
        apolitical_name='Guinea',
    ),
    Country(
        name='Guinea-Bissau',
        alpha2='GW',
        alpha3='GNB',
        numeric=624,
        apolitical_name='Guinea-Bissau',
    ),
    Country(
        name='Guyana',
        alpha2='GY',
        alpha3='GUY',
        numeric=328,
        apolitical_name='Guyana',
    ),
    Country(
        name='Haiti',
        alpha2='HT',
        alpha3='HTI',
        numeric=332,
        apolitical_name='Haiti',
    ),
    Country(
        name='Heard Island and McDonald Islands',
        alpha2='HM',
        alpha3='HMD',
        numeric=334,
        apolitical_name='Heard Island and McDonald Islands',
    ),
    Country(
        name='Holy See',
        alpha2='VA',
        alpha3='VAT',
        numeric=336,
        apolitical_name='Holy See',
    ),
    Country(
        name='Honduras',
        alpha2='HN',
        alpha3='HND',
        numeric=340,
        apolitical_name='Honduras',
    ),
    Country(
        name='Hong Kong',
        alpha2='HK',
        alpha3='HKG',
        numeric=344,
        apolitical_name='Hong Kong',
    ),
    Country(
        name='Hungary',
        alpha2='HU',
        alpha3='HUN',
        numeric=348,
        apolitical_name='Hungary',
    ),
    Country(
        name='Iceland',
        alpha2='IS',
        alpha3='ISL',
        numeric=352,
        apolitical_name='Iceland',
    ),
    Country(
        name='India',
        alpha2='IN',
        alpha3='IND',
        numeric=356,
        apolitical_name='India',
    ),
    Country(
        name='Indonesia',
        alpha2='ID',
        alpha3='IDN',
        numeric=360,
        apolitical_name='Indonesia',
    ),
    Country(
        name='Iran, Islamic Republic of',
        alpha2='IR',
        alpha3='IRN',
        numeric=364,
        apolitical_name='Iran, Islamic Republic of',
    ),
    Country(
        name='Iraq',
        alpha2='IQ',
        alpha3='IRQ',
        numeric=368,
        apolitical_name='Iraq',
    ),
    Country(
        name='Ireland',
        alpha2='IE',
        alpha3='IRL',
        numeric=372,
        apolitical_name='Ireland',
    ),
    Country(
        name='Isle of Man',
        alpha2='IM',
        alpha3='IMN',
        numeric=833,
        apolitical_name='Isle of Man',
    ),
    Country(
        name='Israel',
        alpha2='IL',
        alpha3='ISR',
        numeric=376,
        apolitical_name='Israel',
    ),
    Country(
        name='Italy',
        alpha2='IT',
        alpha3='ITA',
        numeric=380,
        apolitical_name='Italy',
    ),
    Country(
        name='Jamaica',
        alpha2='JM',
        alpha3='JAM',
        numeric=388,
        apolitical_name='Jamaica',
    ),
    Country(
        name='Japan',
        alpha2='JP',
        alpha3='JPN',
        numeric=392,
        apolitical_name='Japan',
    ),
    Country(
        name='Jersey',
        alpha2='JE',
        alpha3='JEY',
        numeric=832,
        apolitical_name='Jersey',
    ),
    Country(
        name='Jordan',
        alpha2='JO',
        alpha3='JOR',
        numeric=400,
        apolitical_name='Jordan',
    ),
    Country(
        name='Kazakhstan',
        alpha2='KZ',
        alpha3='KAZ',
        numeric=398,
        apolitical_name='Kazakhstan',
    ),
    Country(
        name='Kenya',
        alpha2='KE',
        alpha3='KEN',
        numeric=404,
        apolitical_name='Kenya',
    ),
    Country(
        name='Kiribati',
        alpha2='KI',
        alpha3='KIR',
        numeric=296,
        apolitical_name='Kiribati',
    ),
    Country(
        name="Korea, Democratic People's Republic of",
        alpha2='KP',
        alpha3='PRK',
        numeric=408,
        apolitical_name="Korea, Democratic People's Republic of",
    ),
    Country(
        name='Korea, Republic of',
        alpha2='KR',
        alpha3='KOR',
        numeric=410,
        apolitical_name='Korea, Republic of',
    ),
    Country(
        name='Kosovo',
        alpha2='XK',
        alpha3='XKX',
        numeric=983,
        apolitical_name='Kosovo',
    ),
    Country(
        name='Kuwait',
        alpha2='KW',
        alpha3='KWT',
        numeric=414,
        apolitical_name='Kuwait',
    ),
    Country(
        name='Kyrgyzstan',
        alpha2='KG',
        alpha3='KGZ',
        numeric=417,
        apolitical_name='Kyrgyzstan',
    ),
    Country(
        name="Lao People's Democratic Republic",
        alpha2='LA',
        alpha3='LAO',
        numeric=418,
        apolitical_name="Lao People's Democratic Republic",
    ),
    Country(
        name='Latvia',
        alpha2='LV',
        alpha3='LVA',
        numeric=428,
        apolitical_name='Latvia',
    ),
    Country(
        name='Lebanon',
        alpha2='LB',
        alpha3='LBN',
        numeric=422,
        apolitical_name='Lebanon',
    ),
    Country(
        name='Lesotho',
        alpha2='LS',
        alpha3='LSO',
        numeric=426,
        apolitical_name='Lesotho',
    ),
    Country(
        name='Liberia',
        alpha2='LR',
        alpha3='LBR',
        numeric=430,
        apolitical_name='Liberia',
    ),
    Country(
        name='Libya',
        alpha2='LY',
        alpha3='LBY',
        numeric=434,
        apolitical_name='Libya',
    ),
    Country(
        name='Liechtenstein',
        alpha2='LI',
        alpha3='LIE',
        numeric=438,
        apolitical_name='Liechtenstein',
    ),
    Country(
        name='Lithuania',
        alpha2='LT',
        alpha3='LTU',
        numeric=440,
        apolitical_name='Lithuania',
    ),
    Country(
        name='Luxembourg',
        alpha2='LU',
        alpha3='LUX',
        numeric=442,
        apolitical_name='Luxembourg',
    ),
    Country(
        name='Macao',
        alpha2='MO',
        alpha3='MAC',
        numeric=446,
        apolitical_name='Macao',
    ),
    Country(
        name='North Macedonia',
        alpha2='MK',
        alpha3='MKD',
        numeric=807,
        apolitical_name='North Macedonia',
    ),
    Country(
        name='Madagascar',
        alpha2='MG',
        alpha3='MDG',
        numeric=450,
        apolitical_name='Madagascar',
    ),
    Country(
        name='Malawi',
        alpha2='MW',
        alpha3='MWI',
        numeric=454,
        apolitical_name='Malawi',
    ),
    Country(
        name='Malaysia',
        alpha2='MY',
        alpha3='MYS',
        numeric=458,
        apolitical_name='Malaysia',
    ),
    Country(
        name='Maldives',
        alpha2='MV',
        alpha3='MDV',
        numeric=462,
        apolitical_name='Maldives',
    ),
    Country(
        name='Mali',
        alpha2='ML',
        alpha3='MLI',
        numeric=466,
        apolitical_name='Mali',
    ),
    Country(
        name='Malta',
        alpha2='MT',
        alpha3='MLT',
        numeric=470,
        apolitical_name='Malta',
    ),
    Country(
        name='Marshall Islands',
        alpha2='MH',
        alpha3='MHL',
        numeric=584,
        apolitical_name='Marshall Islands',
    ),
    Country(
        name='Martinique',
        alpha2='MQ',
        alpha3='MTQ',
        numeric=474,
        apolitical_name='Martinique',
    ),
    Country(
        name='Mauritania',
        alpha2='MR',
        alpha3='MRT',
        numeric=478,
        apolitical_name='Mauritania',
    ),
    Country(
        name='Mauritius',
        alpha2='MU',
        alpha3='MUS',
        numeric=480,
        apolitical_name='Mauritius',
    ),
    Country(
        name='Mayotte',
        alpha2='YT',
        alpha3='MYT',
        numeric=175,
        apolitical_name='Mayotte',
    ),
    Country(
        name='Mexico',
        alpha2='MX',
        alpha3='MEX',
        numeric=484,
        apolitical_name='Mexico',
    ),
    Country(
        name='Micronesia, Federated States of',
        alpha2='FM',
        alpha3='FSM',
        numeric=583,
        apolitical_name='Micronesia, Federated States of',
    ),
    Country(
        name='Moldova, Republic of',
        alpha2='MD',
        alpha3='MDA',
        numeric=498,
        apolitical_name='Moldova, Republic of',
    ),
    Country(
        name='Monaco',
        alpha2='MC',
        alpha3='MCO',
        numeric=492,
        apolitical_name='Monaco',
    ),
    Country(
        name='Mongolia',
        alpha2='MN',
        alpha3='MNG',
        numeric=496,
        apolitical_name='Mongolia',
    ),
    Country(
        name='Montenegro',
        alpha2='ME',
        alpha3='MNE',
        numeric=499,
        apolitical_name='Montenegro',
    ),
    Country(
        name='Montserrat',
        alpha2='MS',
        alpha3='MSR',
        numeric=500,
        apolitical_name='Montserrat',
    ),
    Country(
        name='Morocco',
        alpha2='MA',
        alpha3='MAR',
        numeric=504,
        apolitical_name='Morocco',
    ),
    Country(
        name='Mozambique',
        alpha2='MZ',
        alpha3='MOZ',
        numeric=508,
        apolitical_name='Mozambique',
    ),
    Country(
        name='Myanmar',
        alpha2='MM',
        alpha3='MMR',
        numeric=104,
        apolitical_name='Myanmar',
    ),
    Country(
        name='Namibia',
        alpha2='',
        alpha3='NAM',
        numeric=516,
        apolitical_name='Namibia',
    ),
    Country(
        name='Nauru',
        alpha2='NR',
        alpha3='NRU',
        numeric=520,
        apolitical_name='Nauru',
    ),
    Country(
        name='Nepal',
        alpha2='NP',
        alpha3='NPL',
        numeric=524,
        apolitical_name='Nepal',
    ),
    Country(
        name='Netherlands',
        alpha2='NL',
        alpha3='NLD',
        numeric=528,
        apolitical_name='Netherlands',
    ),
    Country(
        name='New Caledonia',
        alpha2='NC',
        alpha3='NCL',
        numeric=540,
        apolitical_name='New Caledonia',
    ),
    Country(
        name='New Zealand',
        alpha2='NZ',
        alpha3='NZL',
        numeric=554,
        apolitical_name='New Zealand',
    ),
    Country(
        name='Nicaragua',
        alpha2='NI',
        alpha3='NIC',
        numeric=558,
        apolitical_name='Nicaragua',
    ),
    Country(
        name='Niger',
        alpha2='NE',
        alpha3='NER',
        numeric=562,
        apolitical_name='Niger',
    ),
    Country(
        name='Nigeria',
        alpha2='NG',
        alpha3='NGA',
        numeric=566,
        apolitical_name='Nigeria',
    ),
    Country(
        name='Niue',
        alpha2='NU',
        alpha3='NIU',
        numeric=570,
        apolitical_name='Niue',
    ),
    Country(
        name='Norfolk Island',
        alpha2='NF',
        alpha3='NFK',
        numeric=574,
        apolitical_name='Norfolk Island',
    ),
    Country(
        name='Northern Mariana Islands',
        alpha2='MP',
        alpha3='MNP',
        numeric=580,
        apolitical_name='Northern Mariana Islands',
    ),
    Country(
        name='Norway',
        alpha2='NO',
        alpha3='NOR',
        numeric=578,
        apolitical_name='Norway',
    ),
    Country(
        name='Oman',
        alpha2='OM',
        alpha3='OMN',
        numeric=512,
        apolitical_name='Oman',
    ),
    Country(
        name='Pakistan',
        alpha2='PK',
        alpha3='PAK',
        numeric=586,
        apolitical_name='Pakistan',
    ),
    Country(
        name='Palau',
        alpha2='PW',
        alpha3='PLW',
        numeric=585,
        apolitical_name='Palau',
    ),
    Country(
        name='Palestine, State of',
        alpha2='PS',
        alpha3='PSE',
        numeric=275,
        apolitical_name='Palestine',
    ),
    Country(
        name='Panama',
        alpha2='PA',
        alpha3='PAN',
        numeric=591,
        apolitical_name='Panama',
    ),
    Country(
        name='Papua New Guinea',
        alpha2='PG',
        alpha3='PNG',
        numeric=598,
        apolitical_name='Papua New Guinea',
    ),
    Country(
        name='Paraguay',
        alpha2='PY',
        alpha3='PRY',
        numeric=600,
        apolitical_name='Paraguay',
    ),
    Country(
        name='Peru',
        alpha2='PE',
        alpha3='PER',
        numeric=604,
        apolitical_name='Peru',
    ),
    Country(
        name='Philippines',
        alpha2='PH',
        alpha3='PHL',
        numeric=608,
        apolitical_name='Philippines',
    ),
    Country(
        name='Pitcairn',
        alpha2='PN',
        alpha3='PCN',
        numeric=612,
        apolitical_name='Pitcairn',
    ),
    Country(
        name='Poland',
        alpha2='PL',
        alpha3='POL',
        numeric=616,
        apolitical_name='Poland',
    ),
    Country(
        name='Portugal',
        alpha2='PT',
        alpha3='PRT',
        numeric=620,
        apolitical_name='Portugal',
    ),
    Country(
        name='Puerto Rico',
        alpha2='PR',
        alpha3='PRI',
        numeric=630,
        apolitical_name='Puerto Rico',
    ),
    Country(
        name='Qatar',
        alpha2='QA',
        alpha3='QAT',
        numeric=634,
        apolitical_name='Qatar',
    ),
    Country(
        name='Réunion',
        alpha2='RE',
        alpha3='REU',
        numeric=638,
        apolitical_name='Réunion',
    ),
    Country(
        name='Romania',
        alpha2='RO',
        alpha3='ROU',
        numeric=642,
        apolitical_name='Romania',
    ),
    Country(
        name='Russian Federation',
        alpha2='RU',
        alpha3='RUS',
        numeric=643,
        apolitical_name='Russian Federation',
    ),
    Country(
        name='Rwanda',
        alpha2='RW',
        alpha3='RWA',
        numeric=646,
        apolitical_name='Rwanda',
    ),
    Country(
        name='Saint Barthélemy',
        alpha2='BL',
        alpha3='BLM',
        numeric=652,
        apolitical_name='Saint Barthélemy',
    ),
    Country(
        name='Saint Helena, Ascension and Tristan da Cunha',
        alpha2='SH',
        alpha3='SHN',
        numeric=654,
        apolitical_name='Saint Helena, Ascension and Tristan da Cunha',
    ),
    Country(
        name='Saint Kitts and Nevis',
        alpha2='KN',
        alpha3='KNA',
        numeric=659,
        apolitical_name='Saint Kitts and Nevis',
    ),
    Country(
        name='Saint Lucia',
        alpha2='LC',
        alpha3='LCA',
        numeric=662,
        apolitical_name='Saint Lucia',
    ),
    Country(
        name='Saint Martin (French part)',
        alpha2='MF',
        alpha3='MAF',
        numeric=663,
        apolitical_name='Saint Martin (French part)',
    ),
    Country(
        name='Saint Pierre and Miquelon',
        alpha2='PM',
        alpha3='SPM',
        numeric=666,
        apolitical_name='Saint Pierre and Miquelon',
    ),
    Country(
        name='Saint Vincent and the Grenadines',
        alpha2='VC',
        alpha3='VCT',
        numeric=670,
        apolitical_name='Saint Vincent and the Grenadines',
    ),
    Country(
        name='Samoa',
        alpha2='WS',
        alpha3='WSM',
        numeric=882,
        apolitical_name='Samoa',
    ),
    Country(
        name='San Marino',
        alpha2='SM',
        alpha3='SMR',
        numeric=674,
        apolitical_name='San Marino',
    ),
    Country(
        name='Sao Tome and Principe',
        alpha2='ST',
        alpha3='STP',
        numeric=678,
        apolitical_name='Sao Tome and Principe',
    ),
    Country(
        name='Saudi Arabia',
        alpha2='SA',
        alpha3='SAU',
        numeric=682,
        apolitical_name='Saudi Arabia',
    ),
    Country(
        name='Senegal',
        alpha2='SN',
        alpha3='SEN',
        numeric=686,
        apolitical_name='Senegal',
    ),
    Country(
        name='Serbia',
        alpha2='RS',
        alpha3='SRB',
        numeric=688,
        apolitical_name='Serbia',
    ),
    Country(
        name='Seychelles',
        alpha2='SC',
        alpha3='SYC',
        numeric=690,
        apolitical_name='Seychelles',
    ),
    Country(
        name='Sierra Leone',
        alpha2='SL',
        alpha3='SLE',
        numeric=694,
        apolitical_name='Sierra Leone',
    ),
    Country(
        name='Singapore',
        alpha2='SG',
        alpha3='SGP',
        numeric=702,
        apolitical_name='Singapore',
    ),
    Country(
        name='Sint Maarten (Dutch part)',
        alpha2='SX',
        alpha3='SXM',
        numeric=534,
        apolitical_name='Sint Maarten (Dutch part)',
    ),
    Country(
        name='Slovakia',
        alpha2='SK',
        alpha3='SVK',
        numeric=703,
        apolitical_name='Slovakia',
    ),
    Country(
        name='Slovenia',
        alpha2='SI',
        alpha3='SVN',
        numeric=705,
        apolitical_name='Slovenia',
    ),
    Country(
        name='Solomon Islands',
        alpha2='SB',
        alpha3='SLB',
        numeric=90,
        apolitical_name='Solomon Islands',
    ),
    Country(
        name='Somalia',
        alpha2='SO',
        alpha3='SOM',
        numeric=706,
        apolitical_name='Somalia',
    ),
    Country(
        name='South Africa',
        alpha2='ZA',
        alpha3='ZAF',
        numeric=710,
        apolitical_name='South Africa',
    ),
    Country(
        name='South Georgia and the South Sandwich Islands',
        alpha2='GS',
        alpha3='SGS',
        numeric=239,
        apolitical_name='South Georgia and the South Sandwich Islands',
    ),
    Country(
        name='South Sudan',
        alpha2='SS',
        alpha3='SSD',
        numeric=728,
        apolitical_name='South Sudan',
    ),
    Country(
        name='Spain',
        alpha2='ES',
        alpha3='ESP',
        numeric=724,
        apolitical_name='Spain',
    ),
    Country(
        name='Sri Lanka',
        alpha2='LK',
        alpha3='LKA',
        numeric=144,
        apolitical_name='Sri Lanka',
    ),
    Country(
        name='Sudan',
        alpha2='SD',
        alpha3='SDN',
        numeric=729,
        apolitical_name='Sudan',
    ),
    Country(
        name='Suriname',
        alpha2='SR',
        alpha3='SUR',
        numeric=740,
        apolitical_name='Suriname',
    ),
    Country(
        name='Svalbard and Jan Mayen',
        alpha2='SJ',
        alpha3='SJM',
        numeric=744,
        apolitical_name='Svalbard and Jan Mayen',
    ),
    Country(
        name='Eswatini',
        alpha2='SZ',
        alpha3='SWZ',
        numeric=748,
        apolitical_name='Eswatini',
    ),
    Country(
        name='Sweden',
        alpha2='SE',
        alpha3='SWE',
        numeric=752,
        apolitical_name='Sweden',
    ),
    Country(
        name='Switzerland',
        alpha2='CH',
        alpha3='CHE',
        numeric=756,
        apolitical_name='Switzerland',
    ),
    Country(
        name='Syrian Arab Republic',
        alpha2='SY',
        alpha3='SYR',
        numeric=760,
        apolitical_name='Syrian Arab Republic',
    ),
    Country(
        name='Taiwan, Province of China',
        alpha2='TW',
        alpha3='TWN',
        numeric=158,
        apolitical_name='Taiwan',
    ),
    Country(
        name='Tajikistan',
        alpha2='TJ',
        alpha3='TJK',
        numeric=762,
        apolitical_name='Tajikistan',
    ),
    Country(
        name='Tanzania, United Republic of',
        alpha2='TZ',
        alpha3='TZA',
        numeric=834,
        apolitical_name='Tanzania, United Republic of',
    ),
    Country(
        name='Thailand',
        alpha2='TH',
        alpha3='THA',
        numeric=764,
        apolitical_name='Thailand',
    ),
    Country(
        name='Timor-Leste',
        alpha2='TL',
        alpha3='TLS',
        numeric=626,
        apolitical_name='Timor-Leste',
    ),
    Country(
        name='Togo',
        alpha2='TG',
        alpha3='TGO',
        numeric=768,
        apolitical_name='Togo',
    ),
    Country(
        name='Tokelau',
        alpha2='TK',
        alpha3='TKL',
        numeric=772,
        apolitical_name='Tokelau',
    ),
    Country(
        name='Tonga',
        alpha2='TO',
        alpha3='TON',
        numeric=776,
        apolitical_name='Tonga',
    ),
    Country(
        name='Trinidad and Tobago',
        alpha2='TT',
        alpha3='TTO',
        numeric=780,
        apolitical_name='Trinidad and Tobago',
    ),
    Country(
        name='Tunisia',
        alpha2='TN',
        alpha3='TUN',
        numeric=788,
        apolitical_name='Tunisia',
    ),
    Country(
        name='Türkiye',
        alpha2='TR',
        alpha3='TUR',
        numeric=792,
        apolitical_name='Türkiye',
    ),
    Country(
        name='Turkmenistan',
        alpha2='TM',
        alpha3='TKM',
        numeric=795,
        apolitical_name='Turkmenistan',
    ),
    Country(
        name='Turks and Caicos Islands',
        alpha2='TC',
        alpha3='TCA',
        numeric=796,
        apolitical_name='Turks and Caicos Islands',
    ),
    Country(
        name='Tuvalu',
        alpha2='TV',
        alpha3='TUV',
        numeric=798,
        apolitical_name='Tuvalu',
    ),
    Country(
        name='Uganda',
        alpha2='UG',
        alpha3='UGA',
        numeric=800,
        apolitical_name='Uganda',
    ),
    Country(
        name='Ukraine',
        alpha2='UA',
        alpha3='UKR',
        numeric=804,
        apolitical_name='Ukraine',
    ),
    Country(
        name='United Arab Emirates',
        alpha2='AE',
        alpha3='ARE',
        numeric=784,
        apolitical_name='United Arab Emirates',
    ),
    Country(
        name='United Kingdom of Great Britain and Northern Ireland',
        alpha2='GB',
        alpha3='GBR',
        numeric=826,
        apolitical_name='United Kingdom of Great Britain and Northern Ireland',
    ),
    Country(
        name='United States of America',
        alpha2='US',
        alpha3='USA',
        numeric=840,
        apolitical_name='United States of America',
    ),
    Country(
        name='United States Minor Outlying Islands',
        alpha2='UM',
        alpha3='UMI',
        numeric=581,
        apolitical_name='United States Minor Outlying Islands',
    ),
    Country(
        name='Uruguay',
        alpha2='UY',
        alpha3='URY',
        numeric=858,
        apolitical_name='Uruguay',
    ),
    Country(
        name='Uzbekistan',
        alpha2='UZ',
        alpha3='UZB',
        numeric=860,
        apolitical_name='Uzbekistan',
    ),
    Country(
        name='Vanuatu',
        alpha2='VU',
        alpha3='VUT',
        numeric=548,
        apolitical_name='Vanuatu',
    ),
    Country(
        name='Venezuela, Bolivarian Republic of',
        alpha2='VE',
        alpha3='VEN',
        numeric=862,
        apolitical_name='Venezuela, Bolivarian Republic of',
    ),
    Country(
        name='Viet Nam',
        alpha2='VN',
        alpha3='VNM',
        numeric=704,
        apolitical_name='Viet Nam',
    ),
    Country(
        name='Virgin Islands, British',
        alpha2='VG',
        alpha3='VGB',
        numeric=92,
        apolitical_name='Virgin Islands, British',
    ),
    Country(
        name='Virgin Islands, U.S.',
        alpha2='VI',
        alpha3='VIR',
        numeric=850,
        apolitical_name='Virgin Islands, U.S.',
    ),
    Country(
        name='Wallis and Futuna',
        alpha2='WF',
        alpha3='WLF',
        numeric=876,
        apolitical_name='Wallis and Futuna',
    ),
    Country(
        name='Western Sahara',
        alpha2='EH',
        alpha3='ESH',
        numeric=732,
        apolitical_name='Western Sahara',
    ),
    Country(
        name='Yemen',
        alpha2='YE',
        alpha3='YEM',
        numeric=887,
        apolitical_name='Yemen',
    ),
    Country(
        name='Zambia',
        alpha2='ZM',
        alpha3='ZMB',
        numeric=894,
        apolitical_name='Zambia',
    ),
    Country(
        name='Zimbabwe',
        alpha2='ZW',
        alpha3='ZWE',
        numeric=716,
        apolitical_name='Zimbabwe',
    )
]


