"""
income.py

Defining the income tag.
"""
iso3_to_wb_income_level = {
    "AFG": "Low income",
    "ALA": None,
    "ALB": "Upper middle income",
    "DZA": "Lower middle income",
    "ASM": "High income",
    "AND": "High income",
    "AGO": "Lower middle income",
    "AIA": None,
    "ATA": None,
    "ATG": "High income",
    "ARG": "Upper middle income",
    "ARM": "Upper middle income",
    "ABW": "High income",
    "AUS": "High income",
    "AUT": "High income",
    "AZE": "Upper middle income",
    "BHS": "High income",
    "BHR": "High income",
    "BGD": "Lower middle income",
    "BRB": "High income",
    "BLR": "Upper middle income",
    "BEL": "High income",
    "BLZ": "Upper middle income",
    "BEN": "Lower middle income",
    "BMU": "High income",
    "BTN": "Lower middle income",
    "BOL": "Lower middle income",
    "BES": None,
    "BIH": "Upper middle income",
    "BWA": "Upper middle income",
    "BVT": None,
    "BRA": "Upper middle income",
    "IOT": None,
    "BRN": "High income",
    "BGR": "Upper middle income",
    "BFA": "Low income",
    "BDI": "Low income",
    "KHM": "Lower middle income",
    "CMR": "Lower middle income",
    "CAN": "High income",
    "CPV": "Lower middle income",
    "CYM": "High income",
    "CAF": "Low income",
    "TCD": "Low income",
    "CHL": "High income",
    "CHN": "Upper middle income",
    "CXR": None,
    "CCK": None,
    "COL": "Upper middle income",
    "COM": "Lower middle income",
    "COG": "Lower middle income",
    "COD": "Low income",
    "COK": None,
    "CRI": "Upper middle income",
    "CIV": "Lower middle income",
    "HRV": "High income",
    "CUB": "Upper middle income",
    "CUW": "High income",
    "CYP": "High income",
    "CZE": "High income",
    "DNK": "High income",
    "DJI": "Lower middle income",
    "DMA": "Upper middle income",
    "DOM": "Upper middle income",
    "ECU": "Upper middle income",
    "EGY": "Lower middle income",
    "SLV": "Upper middle income",
    "GNQ": "Upper middle income",
    "ERI": "Low income",
    "EST": "High income",
    "ETH": "Low income",
    "FLK": None,
    "FRO": "High income",
    "FJI": "Upper middle income",
    "FIN": "High income",
    "FRA": "High income",
    "GUF": None,
    "PYF": "High income",
    "ATF": None,
    "GAB": "Upper middle income",
    "GMB": "Low income",
    "GEO": "Upper middle income",
    "DEU": "High income",
    "GHA": "Lower middle income",
    "GIB": "High income",
    "GRC": "High income",
    "GRL": "High income",
    "GRD": "Upper middle income",
    "GLP": None,
    "GUM": "High income",
    "GTM": "Upper middle income",
    "GGY": None,
    "GIN": "Lower middle income",
    "GNB": "Low income",
    "GUY": "High income",
    "HTI": "Lower middle income",
    "HMD": None,
    "VAT": None,
    "HND": "Lower middle income",
    "HKG": "High income",
    "HUN": "High income",
    "ISL": "High income",
    "IND": "Lower middle income",
    "IDN": "Upper middle income",
    "IRN": "Lower middle income",
    "IRQ": "Upper middle income",
    "IRL": "High income",
    "IMN": "High income",
    "ISR": "High income",
    "ITA": "High income",
    "JAM": "Upper middle income",
    "JPN": "High income",
    "JEY": None,
    "JOR": "Lower middle income",
    "KAZ": "Upper middle income",
    "KEN": "Lower middle income",
    "KIR": "Lower middle income",
    "PRK": "Low income",
    "KOR": "High income",
    "XKX": "Upper middle income",
    "KWT": "High income",
    "KGZ": "Lower middle income",
    "LAO": "Lower middle income",
    "LVA": "High income",
    "LBN": "Lower middle income",
    "LSO": "Lower middle income",
    "LBR": "Low income",
    "LBY": "Upper middle income",
    "LIE": "High income",
    "LTU": "High income",
    "LUX": "High income",
    "MAC": "High income",
    "MKD": "Upper middle income",
    "MDG": "Low income",
    "MWI": "Low income",
    "MYS": "Upper middle income",
    "MDV": "Upper middle income",
    "MLI": "Low income",
    "MLT": "High income",
    "MHL": "Upper middle income",
    "MTQ": None,
    "MRT": "Lower middle income",
    "MUS": "Upper middle income",
    "MYT": None,
    "MEX": "Upper middle income",
    "FSM": "Lower middle income",
    "MDA": "Upper middle income",
    "MCO": "High income",
    "MNG": "Lower middle income",
    "MNE": "Upper middle income",
    "MSR": None,
    "MAR": "Lower middle income",
    "MOZ": "Low income",
    "MMR": "Lower middle income",
    "NAM": "Upper middle income",
    "NRU": "High income",
    "NPL": "Lower middle income",
    "NLD": "High income",
    "NCL": "High income",
    "NZL": "High income",
    "NIC": "Lower middle income",
    "NER": "Low income",
    "NGA": "Lower middle income",
    "NIU": None,
    "NFK": None,
    "MNP": "High income",
    "NOR": "High income",
    "OMN": "High income",
    "PAK": "Lower middle income",
    "PLW": "Upper middle income",
    "PSE": "Upper middle income",
    "PAN": "High income",
    "PNG": "Lower middle income",
    "PRY": "Upper middle income",
    "PER": "Upper middle income",
    "PHL": "Lower middle income",
    "PCN": None,
    "POL": "High income",
    "PRT": "High income",
    "PRI": "High income",
    "QAT": "High income",
    "REU": None,
    "ROU": "High income",
    "RUS": "Upper middle income",
    "RWA": "Low income",
    "BLM": None,
    "SHN": None,
    "KNA": "High income",
    "LCA": "Upper middle income",
    "MAF": "High income",
    "SPM": None,
    "VCT": "Upper middle income",
    "WSM": "Lower middle income",
    "SMR": "High income",
    "STP": "Lower middle income",
    "SAU": "High income",
    "SEN": "Lower middle income",
    "SRB": "Upper middle income",
    "SYC": "High income",
    "SLE": "Low income",
    "SGP": "High income",
    "SXM": "High income",
    "SVK": "High income",
    "SVN": "High income",
    "SLB": "Lower middle income",
    "SOM": "Low income",
    "ZAF": "Upper middle income",
    "SGS": None,
    "SSD": "Low income",
    "ESP": "High income",
    "LKA": "Lower middle income",
    "SDN": "Low income",
    "SUR": "Upper middle income",
    "SJM": None,
    "SWZ": "Lower middle income",
    "SWE": "High income",
    "CHE": "High income",
    "SYR": "Low income",
    "TWN": "High income",
    "TJK": "Lower middle income",
    "TZA": "Lower middle income",
    "THA": "Upper middle income",
    "TLS": "Lower middle income",
    "TGO": "Low income",
    "TKL": None,
    "TON": "Upper middle income",
    "TTO": "High income",
    "TUN": "Lower middle income",
    "TUR": "Upper middle income",
    "TKM": "Upper middle income",
    "TCA": "High income",
    "TUV": "Upper middle income",
    "UGA": "Low income",
    "UKR": "Lower middle income",
    "ARE": "High income",
    "GBR": "High income",
    "USA": "High income",
    "UMI": None,
    "URY": "High income",
    "UZB": "Lower middle income",
    "VUT": "Lower middle income",
    "VEN": None,
    "VNM": "Lower middle income",
    "VGB": "High income",
    "VIR": "High income",
    "WLF": None,
    "ESH": None,
    "YEM": "Low income",
    "ZMB": "Lower middle income",
    "ZWE": "Lower middle income"
}
