"""
who_region.py

Defining the WHO Region tag
"""
ccn3_to_who_region = {
    67: "Andean Latin America",
    219: "Andean Latin America",
    605: "Andean Latin America",
    36: "Australasia",
    554: "Australasia",
    28: "Caribbean",
    44: "Caribbean",
    52: "Caribbean",
    84: "Caribbean",
    192: "Caribbean",
    214: "Caribbean",
    214: "Caribbean",
    308: "Caribbean",
    328: "Caribbean",
    332: "Caribbean",
    388: "Caribbean",
    662: "Caribbean",
    670: "Caribbean",
    740: "Caribbean",
    659: "Caribbean",
    780: "Caribbean",
    51: "Central Asia",
    31: "Central Asia",
    268: "Central Asia",
    398: "Central Asia",
    417: "Central Asia",
    496: "Central Asia",
    762: "Central Asia",
    795: "Central Asia",
    860: "Central Asia",
    8: "Central Europe",
    70: "Central Europe",
    100: "Central Europe",
    191: "Central Europe",
    203: "Central Europe",
    348: "Central Europe",
    807: "Central Europe",
    499: "Central Europe",
    616: "Central Europe",
    642: "Central Europe",
    688: "Central Europe",
    703: "Central Europe",
    705: "Central Europe",
    170: "Central Latin America",
    188: "Central Latin America",
    222: "Central Latin America",
    320: "Central Latin America",
    340: "Central Latin America",
    484: "Central Latin America",
    558: "Central Latin America",
    591: "Central Latin America",
    862: "Central Latin America",
    24: "Central sub-Saharan Africa",
    140: "Central sub-Saharan Africa",
    178: "Central sub-Saharan Africa",
    180: "Central sub-Saharan Africa",
    226: "Central sub-Saharan Africa",
    266: "Central sub-Saharan Africa",
    156: "East Asia",
    408: "East Asia",
    158: "East Asia",
    112: "Eastern Europe",
    233: "Eastern Europe",
    428: "Eastern Europe",
    440: "Eastern Europe",
    498: "Eastern Europe",
    643: "Eastern Europe",
    804: "Eastern Europe",
    108: "Eastern sub-Saharan Africa",
    174: "Eastern sub-Saharan Africa",
    262: "Eastern sub-Saharan Africa",
    232: "Eastern sub-Saharan Africa",
    231: "Eastern sub-Saharan Africa",
    404: "Eastern sub-Saharan Africa",
    450: "Eastern sub-Saharan Africa",
    454: "Eastern sub-Saharan Africa",
    480: "Eastern sub-Saharan Africa",
    508: "Eastern sub-Saharan Africa",
    646: "Eastern sub-Saharan Africa",
    690: "Eastern sub-Saharan Africa",
    706: "Eastern sub-Saharan Africa",
    729: "Eastern sub-Saharan Africa",
    834: "Eastern sub-Saharan Africa",
    800: "Eastern sub-Saharan Africa",
    894: "Eastern sub-Saharan Africa",
    96: "High-income Asia Pacific",
    392: "High-income Asia Pacific",
    410: "High-income Asia Pacific",
    702: "High-income Asia Pacific",
    124: "North America, High Income",
    840: "North America, High Income",
    12: "North Africa and Middle East",
    48: "North Africa and Middle East",
    818: "North Africa and Middle East",
    364: "North Africa and Middle East",
    368: "North Africa and Middle East",
    400: "North Africa and Middle East",
    414: "North Africa and Middle East",
    422: "North Africa and Middle East",
    434: "North Africa and Middle East",
    504: "North Africa and Middle East",
    275: "North Africa and Middle East",
    512: "North Africa and Middle East",
    634: "North Africa and Middle East",
    682: "North Africa and Middle East",
    760: "North Africa and Middle East",
    788: "North Africa and Middle East",
    792: "North Africa and Middle East",
    784: "North Africa and Middle East",
    887: "North Africa and Middle East",
    242: "Oceania",
    296: "Oceania",
    583: "Oceania",
    954: "Oceania",
    598: "Oceania",
    882: "Oceania",
    90: "Oceania",
    776: "Oceania",
    548: "Oceania",
    4: "South Asia",
    50: "South Asia",
    64: "South Asia",
    356: "South Asia",
    524: "South Asia",
    586: "South Asia",
    116: "Southeast Asia",
    360: "Southeast Asia",
    418: "Southeast Asia",
    458: "Southeast Asia",
    462: "Southeast Asia",
    104: "Southeast Asia",
    608: "Southeast Asia",
    144: "Southeast Asia",
    764: "Southeast Asia",
    626: "Southeast Asia",
    704: "Southeast Asia",
    32: "Southern Latin America",
    152: "Southern Latin America",
    858: "Southern Latin America",
    72: "Southern sub-Saharan Africa",
    426: "Southern sub-Saharan Africa",
    516: "Southern sub-Saharan Africa",
    710: "Southern sub-Saharan Africa",
    748: "Southern sub-Saharan Africa",
    716: "Southern sub-Saharan Africa",
    76: "Tropical Latin America",
    600: "Tropical Latin America",
    724: "Western Europe",
    40: "Western Europe",
    56: "Western Europe",
    196: "Western Europe",
    208: "Western Europe",
    246: "Western Europe",
    250: "Western Europe",
    276: "Western Europe",
    300: "Western Europe",
    352: "Western Europe",
    372: "Western Europe",
    376: "Western Europe",
    380: "Western Europe",
    442: "Western Europe",
    470: "Western Europe",
    528: "Western Europe",
    578: "Western Europe",
    620: "Western Europe",
    724: "Western Europe",
    752: "Western Europe",
    756: "Western Europe",
    826: "Western Europe",
    204: "Western sub-Saharan Africa",
    854: "Western sub-Saharan Africa",
    120: "Western sub-Saharan Africa",
    132: "Western sub-Saharan Africa",
    148: "Western sub-Saharan Africa",
    384: "Western sub-Saharan Africa",
    270: "Western sub-Saharan Africa",
    288: "Western sub-Saharan Africa",
    324: "Western sub-Saharan Africa",
    624: "Western sub-Saharan Africa",
    430: "Western sub-Saharan Africa",
    466: "Western sub-Saharan Africa",
    478: "Western sub-Saharan Africa",
    562: "Western sub-Saharan Africa",
    566: "Western sub-Saharan Africa",
    678: "Western sub-Saharan Africa",
    686: "Western sub-Saharan Africa",
    694: "Western sub-Saharan Africa",
    768: "Western sub-Saharan Africa",
    5733: "Western sub-Saharan Africa",
}
