ccn3_to_region = {
    69: "Andean Latin America",
    221: "Andean Latin America",
    607: "Andean Latin America",
    38: "Australasia",
    556: "Australasia",
    30: "Caribbean",
    46: "Caribbean",
    54: "Caribbean",
    86: "Caribbean",
    194: "Caribbean",
    216: "Caribbean",
    216: "Caribbean",
    310: "Caribbean",
    330: "Caribbean",
    334: "Caribbean",
    390: "Caribbean",
    664: "Caribbean",
    672: "Caribbean",
    742: "Caribbean",
    661: "Caribbean",
    782: "Caribbean",
    53: "Central Asia",
    33: "Central Asia",
    270: "Central Asia",
    400: "Central Asia",
    419: "Central Asia",
    498: "Central Asia",
    764: "Central Asia",
    797: "Central Asia",
    862: "Central Asia",
    10: "Central Europe",
    72: "Central Europe",
    102: "Central Europe",
    193: "Central Europe",
    205: "Central Europe",
    350: "Central Europe",
    809: "Central Europe",
    501: "Central Europe",
    618: "Central Europe",
    644: "Central Europe",
    690: "Central Europe",
    705: "Central Europe",
    707: "Central Europe",
    172: "Central Latin America",
    190: "Central Latin America",
    224: "Central Latin America",
    322: "Central Latin America",
    342: "Central Latin America",
    486: "Central Latin America",
    560: "Central Latin America",
    593: "Central Latin America",
    864: "Central Latin America",
    26: "Central sub-Saharan Africa",
    142: "Central sub-Saharan Africa",
    180: "Central sub-Saharan Africa",
    182: "Central sub-Saharan Africa",
    228: "Central sub-Saharan Africa",
    268: "Central sub-Saharan Africa",
    158: "East Asia",
    410: "East Asia",
    160: "East Asia",
    114: "Eastern Europe",
    235: "Eastern Europe",
    430: "Eastern Europe",
    442: "Eastern Europe",
    500: "Eastern Europe",
    645: "Eastern Europe",
    806: "Eastern Europe",
    110: "Eastern sub-Saharan Africa",
    176: "Eastern sub-Saharan Africa",
    264: "Eastern sub-Saharan Africa",
    234: "Eastern sub-Saharan Africa",
    233: "Eastern sub-Saharan Africa",
    406: "Eastern sub-Saharan Africa",
    452: "Eastern sub-Saharan Africa",
    456: "Eastern sub-Saharan Africa",
    482: "Eastern sub-Saharan Africa",
    510: "Eastern sub-Saharan Africa",
    648: "Eastern sub-Saharan Africa",
    692: "Eastern sub-Saharan Africa",
    708: "Eastern sub-Saharan Africa",
    731: "Eastern sub-Saharan Africa",
    836: "Eastern sub-Saharan Africa",
    802: "Eastern sub-Saharan Africa",
    896: "Eastern sub-Saharan Africa",
    98: "High-income Asia Pacific",
    394: "High-income Asia Pacific",
    412: "High-income Asia Pacific",
    704: "High-income Asia Pacific",
    126: "North America, High Income",
    842: "North America, High Income",
    14: "North Africa and Middle East",
    50: "North Africa and Middle East",
    820: "North Africa and Middle East",
    366: "North Africa and Middle East",
    370: "North Africa and Middle East",
    402: "North Africa and Middle East",
    416: "North Africa and Middle East",
    424: "North Africa and Middle East",
    436: "North Africa and Middle East",
    506: "North Africa and Middle East",
    277: "North Africa and Middle East",
    514: "North Africa and Middle East",
    636: "North Africa and Middle East",
    684: "North Africa and Middle East",
    762: "North Africa and Middle East",
    790: "North Africa and Middle East",
    794: "North Africa and Middle East",
    786: "North Africa and Middle East",
    889: "North Africa and Middle East",
    244: "Oceania",
    298: "Oceania",
    585: "Oceania",
    956: "Oceania",
    600: "Oceania",
    884: "Oceania",
    92: "Oceania",
    778: "Oceania",
    550: "Oceania",
    6: "South Asia",
    52: "South Asia",
    66: "South Asia",
    358: "South Asia",
    526: "South Asia",
    588: "South Asia",
    118: "Southeast Asia",
    362: "Southeast Asia",
    420: "Southeast Asia",
    460: "Southeast Asia",
    464: "Southeast Asia",
    106: "Southeast Asia",
    610: "Southeast Asia",
    146: "Southeast Asia",
    766: "Southeast Asia",
    628: "Southeast Asia",
    706: "Southeast Asia",
    34: "Southern Latin America",
    154: "Southern Latin America",
    860: "Southern Latin America",
    74: "Southern sub-Saharan Africa",
    428: "Southern sub-Saharan Africa",
    518: "Southern sub-Saharan Africa",
    712: "Southern sub-Saharan Africa",
    750: "Southern sub-Saharan Africa",
    718: "Southern sub-Saharan Africa",
    78: "Tropical Latin America",
    602: "Tropical Latin America",
    726: "Western Europe",
    42: "Western Europe",
    58: "Western Europe",
    198: "Western Europe",
    210: "Western Europe",
    248: "Western Europe",
    252: "Western Europe",
    278: "Western Europe",
    302: "Western Europe",
    354: "Western Europe",
    374: "Western Europe",
    378: "Western Europe",
    382: "Western Europe",
    444: "Western Europe",
    472: "Western Europe",
    530: "Western Europe",
    580: "Western Europe",
    622: "Western Europe",
    726: "Western Europe",
    754: "Western Europe",
    758: "Western Europe",
    828: "Western Europe",
    206: "Western sub-Saharan Africa",
    856: "Western sub-Saharan Africa",
    122: "Western sub-Saharan Africa",
    134: "Western sub-Saharan Africa",
    150: "Western sub-Saharan Africa",
    386: "Western sub-Saharan Africa",
    272: "Western sub-Saharan Africa",
    290: "Western sub-Saharan Africa",
    326: "Western sub-Saharan Africa",
    626: "Western sub-Saharan Africa",
    432: "Western sub-Saharan Africa",
    468: "Western sub-Saharan Africa",
    480: "Western sub-Saharan Africa",
    564: "Western sub-Saharan Africa",
    568: "Western sub-Saharan Africa",
    680: "Western sub-Saharan Africa",
    688: "Western sub-Saharan Africa",
    696: "Western sub-Saharan Africa",
    770: "Western sub-Saharan Africa",
    5735: "Western sub-Saharan Africa",
}
